//Register 
###
POST http://localhost:6969/user/
Content-Type: application/json

{
    "username":"luan123",
    "password":"luan"
}
//Login
###
POST http://localhost:6969/user/login
Content-Type: application/json

{
    "username":"luan123",
    "password":"luan"
}