//Register 
###
POST http://localhost:6969/user/
Content-Type: application/json

{
    "username":"luan123",
    "password":"luan"
}
//get all user 
###
GET http://localhost:6969/user/

//Login
###
POST http://localhost:6969/user/login
Content-Type: application/json

{
    "username":"luan123",
    "password":"luan"
}


//add schedule
###
POST http://localhost:6969/schedule/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRXhpc3QiOiI2Mzg0MjM3ZGM5MGZiYmRiMjlkNjhkMDkiLCJpYXQiOjE2Njk3NDI4MDZ9.daoOBJnhFCqFmfsdYnZ39QYWHQ5DtgH_BedwFuYnxPw

{
    "title":"off",
    "content":"Ban viec hoc tren truong",
    "ispublic":true,
    "ListUserAccess":[]
}
//get all schedule
###
GET http://localhost:6969/schedule/
